### ISSUE TITLE
[EPIC] Run images via jupyter notebook spawner from repo commit 

### ISSUE THREAD

**Issue by Gkrumbach07** [open-services-group/byon#49]
**Is your feature request related to a problem? Please describe.**
As an ODH Admin, I want to be able to create new notebook images from scratch by committing a notebook file to a repository and opening an issue assigned to a bot, so that I can run the images via Jupyter Notebook Spawner.

**Describe the solution you'd like**
I want to be able to create as many PRs I want before I decide to rebuild the jupyter notebook image. Then I can open a template issue assigned to a bot that triggers a new image build with my latest changes. The issue should be closed automatically but also include a link to the image that was hosted.

**Acceptance Criteria**
- [x] https://github.com/open-services-group/byon/issues/50
- [x] https://github.com/open-services-group/byon/issues/51
- [x] https://github.com/open-services-group/byon/issues/54

**Additional context**
related: https://github.com/open-services-group/scrum/issues/15

**Comment by goern** [comment]
@Gkrumbach07 pls sync this issue with https://github.com/open-services-group/scrum/issues/27

**Comment by goern** [comment]
any updates on this?
